// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5dNHtZq7eYFZOsUI1cG8pPZR8eiIn_RU',
    appId: '1:65494028868:web:9fffe85195666ede322211',
    messagingSenderId: '65494028868',
    projectId: 'xblog-auth-eb2d8',
    authDomain: 'xblog-auth-eb2d8.firebaseapp.com',
    storageBucket: 'xblog-auth-eb2d8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE-gC4OvelTMfk2nqa23LLBKZvRpVHWh8',
    appId: '1:65494028868:android:678af81f69c1e96a322211',
    messagingSenderId: '65494028868',
    projectId: 'xblog-auth-eb2d8',
    storageBucket: 'xblog-auth-eb2d8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3nxBbdmBG2X776G1dOdNKMVb1kjZ02Y4',
    appId: '1:65494028868:ios:fe543f7b51bedc3f322211',
    messagingSenderId: '65494028868',
    projectId: 'xblog-auth-eb2d8',
    storageBucket: 'xblog-auth-eb2d8.firebasestorage.app',
    iosClientId: '65494028868-1e027djmrkmet6riq92nppcv1do16259.apps.googleusercontent.com',
    iosBundleId: 'com.example.xblog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3nxBbdmBG2X776G1dOdNKMVb1kjZ02Y4',
    appId: '1:65494028868:ios:fe543f7b51bedc3f322211',
    messagingSenderId: '65494028868',
    projectId: 'xblog-auth-eb2d8',
    storageBucket: 'xblog-auth-eb2d8.firebasestorage.app',
    iosClientId: '65494028868-1e027djmrkmet6riq92nppcv1do16259.apps.googleusercontent.com',
    iosBundleId: 'com.example.xblog',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5dNHtZq7eYFZOsUI1cG8pPZR8eiIn_RU',
    appId: '1:65494028868:web:3ddd1ae71f398f77322211',
    messagingSenderId: '65494028868',
    projectId: 'xblog-auth-eb2d8',
    authDomain: 'xblog-auth-eb2d8.firebaseapp.com',
    storageBucket: 'xblog-auth-eb2d8.firebasestorage.app',
  );
}
